//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesMaintenaceAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDetails
    {
        public int Id { get; set; }
        public Nullable<int> IdProcess { get; set; }
        public Nullable<int> Weight_File { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
