//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesMaintenaceAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArchivo
    {
        public int IdFileType { get; set; }
        public string Descriptions { get; set; }
    }
}
